[versions]
coroutines = "1.6.3"
serialization = "1.3.3"
datetime = "0.3.3"
ktoml = "0.2.11"
cli = "0.3.5"

[libraries]
cli = { module="org.jetbrains.kotlinx:kotlinx-cli", version.ref = "cli" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
serialization-toml-core = { module = "com.akuleshov7:ktoml-core", version.ref = "ktoml" }

datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }